spring.application.name=springproject1
spring.datasource.url=jdbc:mysql://localhost:3306/mandidb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
```

---

### \u0B89\u0BA9\u0BCD MySQL password \u0BAA\u0BCB\u0B9F\u0BC1:
```
spring.datasource.password=root


```
MYSQLHOST=mysql.railway.internal
MYSQLPORT=3306
MYSQLDATABASE= railway
MYSQLUSER=root
MYSQLPASSWORD= YtTegeMvfsgcpLcApIpYIrldgMdOwbgY
                       
