spring.application.name=springproject1
server.port=8080
spring.datasource.url=jdbc:postgresql://dpg-d6uh2j7gi27c73e8f8vg-a/mandi_db_6yfa
spring.datasource.username=mandi_db_6yfa_user
spring.datasource.password=KhbDqOJYvwJipGzX6guusLyW3N5mHQt1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect